spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jwt_secret: ${JWT_SECRET:VVd2Y2cjSSFreyY/YkBATDNfeWtJQU9xQyssMUQsYUc=}
